# This file was generated by GoReleaser. DO NOT EDIT.
class Sepia < Formula
  desc "A minimal interpreted language."
  homepage "https://github.com/rishiosaur/sepia"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rishiosaur/sepia/releases/download/v0.1.3/sepia_0.1.3_darwin_amd64.tar.gz"
    sha256 "06f7621ff477e0edf1546629efdd7f5570c33fcf471177c2ff45667876c36048"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/rishiosaur/sepia/releases/download/v0.1.3/sepia_0.1.3_linux_amd64.tar.gz"
    sha256 "592a86ca7797efb449fba2274f5fa2a8814dc0879835a55fea3d93a842d010d8"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/rishiosaur/sepia/releases/download/v0.1.3/sepia_0.1.3_linux_armv6.tar.gz"
    sha256 "2be3bf72e0a62133cdfb2c7c9b889ff88dba3b24d29bf646173c612a57efebc3"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/rishiosaur/sepia/releases/download/v0.1.3/sepia_0.1.3_linux_arm64.tar.gz"
    sha256 "cfaf0be3e2cffe69d8d14bc9d0622b668a0c9c577954c6b537fc792e0a12ab48"
  end

  def install
    bin.install "sepia"
  end
end
